apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/bases/signalcraft.io_signalcraftalertpolicies.yaml
  - rbac/role.yaml
  - manager/secret.yaml
  - manager/manager.yaml
  - samples/signalcraft_v1alpha1_signalcraftalertpolicy.yaml
