apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: signalcraft-operator
rules:
  - apiGroups:
      - signalcraft.io
    resources:
      - signalcraftalertpolicies
      - signalcraftalertpolicies/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
